///////////////////////////////////////////////////////////
//  Department.cs
//  Implementation of the Class Department
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:16
//  Original author: hazaip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using HospitalManagement;
namespace HospitalManagement {
	public class Department : Unit {

		private List<Ward> wards;

		public Department(){

		}

		~Department(){

		}

		public override List<Ward> Wards{
			get{
				return name;
			}
		}

	}//end Department

}//end namespace HospitalManagement