///////////////////////////////////////////////////////////
//  Employee.cs
//  Implementation of the Class Employee
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:16
//  Original author: Peet
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ApplicationManagement;
namespace HospitalManagement {
	public class Employee : Person {

		private int salary;
		private ApplicationManagement.Role role;

		public Employee(){

		}

		~Employee(){

		}

		public Ward Ward{
			get;
			set;
		}

		public Role Role{
			get;
			set;
		}

		public int Salary{
			get{
				return salary;
			}
			set{
				salary = value;
			}
		}

	}//end Employee

}//end namespace HospitalManagement