///////////////////////////////////////////////////////////
//  Hospital.cs
//  Implementation of the Class Hospital
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:16
//  Original author: hazaip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using HospitalManagement;
namespace HospitalManagement {
	public class Hospital : Unit {

		private string address = "1234 Budapest, Gyógyító tér 1.";
		private List<Department> departments;

		public Hospital(){

		}

		~Hospital(){

		}

		public string Address{
			get{
				return address;
			}
			set{
				address = value;
			}
		}

		public List<Department> Departments{
			get;
			set;
		}

	}//end Hospital

}//end namespace HospitalManagement