///////////////////////////////////////////////////////////
//  Ward.cs
//  Implementation of the Class Ward
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:19
//  Original author: hazaip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using HospitalManagement;
namespace HospitalManagement {
	public class Ward : Unit {

		public Ward(){

		}

		~Ward(){

		}

	}//end Ward

}//end namespace HospitalManagement