///////////////////////////////////////////////////////////
//  IInventoryManagement.cs
//  Implementation of the Interface IInventoryManagement
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:17
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.InventoryManagement;
using HubaskyHospitalManager.Model.Common;

namespace HubaskyHospitalManager.Model.InventoryManagement
{
	public interface IInventoryManagement  {

		/// 
		/// <param name="name"></param>
		/// <param name="quantity"></param>
		/// <param name="unit"></param>
		InventoryItem CreateNewInventoryItem(string name, int quantity, InventoryUnit unit);

		/// 
		/// <param name="item"></param>
		/// <param name="increment"></param>
		int UpdateQuantity(InventoryItem item, int increment);
	}//end IInventoryManagement

}//end namespace InventoryManagement