///////////////////////////////////////////////////////////
//  InventoryManager.cs
//  Implementation of the Class InventoryManager
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:17
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.InventoryManagement;
using HubaskyHospitalManager.Model.ApplicationManagement;
using HubaskyHospitalManager.Model.Common;

namespace HubaskyHospitalManager.Model.InventoryManagement
{
	public class InventoryManager : IInventoryManagement
    {
        private int nextId;
        private List<InventoryItem> inventory;
        private ApplicationManager appManager;

        public int NextId
        {
            get { return nextId; }
            set { nextId = value; }
        }
        
        public List<InventoryItem> Inventory
        {
            get { return inventory; }
            set { inventory = value; }
        }

        public ApplicationManager AppManager
        {
            get { return appManager; }
            set { appManager = value; }
        }

		public InventoryManager()
        {

		}


		/// 
		/// <param name="name"></param>
		/// <param name="quantity"></param>
		/// <param name="unit"></param>
		public InventoryItem CreateNewInventoryItem(string name, int quantity, InventoryUnit unit)
        {

			return null;
		}

		/// 
		/// <param name="item"></param>
		/// <param name="increment"></param>
		public int IncreaseQuantity(InventoryItem item, int increment)
        {

			return 0;
		}
        
		/// 
		/// <param name="item"></param>
		/// <param name="increment"></param>
		public int UpdateQuantity(InventoryItem item, int increment)
        {

			return 0;
		}

	}//end InventoryManager

}//end namespace InventoryManagement