///////////////////////////////////////////////////////////
//  InventoryItem.cs
//  Implementation of the Class InventoryItem
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:17
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.InventoryManagement;
using HubaskyHospitalManager.Model.Common;

namespace HubaskyHospitalManager.Model.InventoryManagement
{
	public class InventoryItem
    {
        private int id;
        private string name;
        private int quantity;
        private InventoryUnit unit;

        public int Id
        {
            get { return id; }
            set { id = value; }
        }

        public string Name
        {
            get { return name; }
            set { name = value; }
        }

        public int Quantity
        {
            get { return quantity; }
            set { quantity = value; }
        }

        public InventoryUnit Unit
        {
            get { return unit; }
            set { unit = value; }
        }

		public InventoryItem()
        {

		}

	}//end InventoryItem

}//end namespace InventoryManagement