///////////////////////////////////////////////////////////
//  Department.cs
//  Implementation of the Class Department
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:16
//  Original author: hazaip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.HospitalManagement;
using HubaskyHospitalManager.Model.Common;

namespace HubaskyHospitalManager.Model.HospitalManagement
{
	public class Department : Unit
    {
        public virtual List<Ward> Wards { get; set; }

		public Department()
        {
            Wards = new List<Ward>();
		}

        public Department(string name, Employee manager, string email, string phone, string web) : base(name, manager, email, phone, web)
        {
            Wards = new List<Ward>();
        }

        public Department(Unit unit)
        {
            Name = unit.Name;
            Manager = unit.Manager;
            Email = unit.Email;
            Phone = unit.Phone;
            Web = unit.Web;
            Employees = new List<Employee>();
            Wards = new List<Ward>();
        }
	}
}