///////////////////////////////////////////////////////////
//  Department.cs
//  Implementation of the Class Department
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:16
//  Original author: hazaip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.HospitalManagement;

namespace HubaskyHospitalManager.Model.HospitalManagement
{
	public class Department : Unit
    {
        private List<Ward> wards;

        public List<Ward> Wards
        {
            get { return wards; }
            set { wards = value; }
        }

		public Department()
        {

		}


	}//end Department

}//end namespace HospitalManagement