///////////////////////////////////////////////////////////
//  HospitalManager.cs
//  Implementation of the Class HospitalManager
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:16
//  Original author: hazaip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.ApplicationManagement;
using HubaskyHospitalManager.Model.HospitalManagement;
using HubaskyHospitalManager.Model.Common;
using System.Linq;
using System.Windows;

namespace HubaskyHospitalManager.Model.HospitalManagement
{
	public class HospitalManager : IManageableUnit, IManageableEmployee {

        public Hospital Hospital { get; set; }
        public ApplicationManager AppManager { get; set; }

		public HospitalManager(ApplicationManager appMgr)
        {
            this.AppManager = appMgr;
            Hospital = new Hospital();
            Hospital = AppManager.ApplicationDb.Hospital.FirstOrDefault();
		}
        
		/// 
		/// <param name="employee"></param>
		/// <param name="ward"></param>
		public void AddEmployee(Employee employee, Ward ward)
        {

		}

		/// 
		/// <param name="unit"></param>
		/// <param name="parentUnit"></param>
		public void AddUnit(Unit unit, Unit parentUnit)
        {

		}

		/// 
		/// <param name="unit"></param>
		public Unit FindParentUnit(Unit unit)
        {

			return null;
		}

		/// 
		/// <param name="employee"></param>
		public void RemoveEmployee(Employee employee)
        {

		}

		/// 
		/// <param name="unit"></param>
		public void RemoveUnit(Unit unit)
        {

		}

		public void UpdateDatabase()
        {

		}

		/// 
		/// <param name="sourceEmployee"></param>
		/// <param name="targetEmployee"></param>
		public void UpdateEmployee(Employee sourceEmployee, Employee targetEmployee)
        {

		}

		/// 
		/// <param name="sourceUnit"></param>
		/// <param name="targetUnit"></param>
		public void UpdateUnit(Unit sourceUnit, Unit targetUnit)
        {

		}

	}//end HospitalManager

}//end namespace HospitalManagement