///////////////////////////////////////////////////////////
//  HospitalManager.cs
//  Implementation of the Class HospitalManager
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:16
//  Original author: hazaip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.ApplicationManagement;
using HubaskyHospitalManager.Model.HospitalManagement;
using HubaskyHospitalManager.Model.Common;
using System.Linq;
using System.Windows;
using HubaskyHospitalManager.Model.Exceptions;

namespace HubaskyHospitalManager.Model.HospitalManagement
{
	public class HospitalManager : IManageableUnit, IManageableEmployee {

        public Hospital Hospital { get; set; }
        public ApplicationManager AppManager { get; set; }

		public HospitalManager(ApplicationManager appMgr)
        {
            this.AppManager = appMgr;
            if (AppManager.ApplicationDb.Hospital.FirstOrDefault() == null)
            {
                Hospital = new Hospital();
                Hospital.Name = "Hubasky Magánkórház";
                Hospital.Address = "1234 Budapest, Gyógyító tér 1.";
                Hospital.Phone = "+36556667788";
                Hospital.Email = "info@hubasky.hu";
                Hospital.Web = "hubasky.hu";
                AppManager.ApplicationDb.Hospital.Add(Hospital);
                AppManager.ApplicationDb.SaveChanges();
            }
            else
                Hospital = AppManager.ApplicationDb.Hospital.FirstOrDefault();
		}
        
		/// 
		/// <param name="employee"></param>
		/// <param name="ward"></param>
		public void AddEmployee(Employee employee, Ward ward)
        {

		}

		/// 
		/// <param name="unit"></param>
		/// <param name="parentUnit"></param>
		public void AddUnit(Unit unit, Unit parentUnit)
        {
            if (unit == null)
                throw new InvalidUnitAdditionException("Unit to be added to the database can't be null.");

            // If parentUnit is null or Hospital type, the unit needs to be converted to Department
            if (parentUnit == null || parentUnit.GetType() == Hospital.GetType())
            {
                Hospital.Departments.Add(new Department(unit));
                AppManager.ApplicationDb.SaveChanges();
            }
            else
            {
                // If the given unit is ward type, the parent unit must be department
                if (parentUnit != null && parentUnit.GetType() == Hospital.Departments.FirstOrDefault().GetType())
                {
                    Department dept = (Department)parentUnit;
                    dept.Wards.Add(new Ward(unit));
                    AppManager.ApplicationDb.SaveChanges();
                }
            }
		}

		/// 
		/// <param name="unit"></param>
		public Unit FindParentUnit(Unit unit)
        {

			return null;
		}

		/// 
		/// <param name="employee"></param>
		public void RemoveEmployee(Employee employee)
        {

		}

		/// 
		/// <param name="unit"></param>
		public void RemoveUnit(Unit unit)
        {

            if (unit != null)
            {
                if (unit.GetType() == AppManager.ApplicationDb.Departments.FirstOrDefault().GetType())
                {
                    AppManager.ApplicationDb.Departments.Remove((Department)unit);
                    AppManager.ApplicationDb.SaveChanges();
                }
                else
                    if (unit.GetType() == AppManager.ApplicationDb.Wards.FirstOrDefault().GetType())
                    {
                        AppManager.ApplicationDb.Wards.Remove((Ward)unit);
                        AppManager.ApplicationDb.SaveChanges();
                    }
            }
		}

		public void UpdateDatabase()
        {

		}

		/// 
		/// <param name="sourceEmployee"></param>
		/// <param name="targetEmployee"></param>
		public void UpdateEmployee(Employee sourceEmployee, Employee targetEmployee)
        {

		}

		/// 
		/// <param name="sourceUnit"></param>
		/// <param name="targetUnit"></param>
		public void UpdateUnit(Unit sourceUnit, Unit targetUnit)
        {

		}

	}//end HospitalManager

}//end namespace HospitalManagement