///////////////////////////////////////////////////////////
//  IManageableUnit.cs
//  Implementation of the Interface IManageableUnit
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:17
//  Original author: justo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.HospitalManagement;

namespace HubaskyHospitalManager.Model.HospitalManagement
{
	public interface IManageableUnit  {

		/// 
		/// <param name="unit"></param>
		/// <param name="parentUnit"></param>
		void AddUnit(Unit unit, Unit parentUnit);

		/// 
		/// <param name="unit"></param>
		void RemoveUnit(Unit unit);

		/// 
		/// <param name="sourceUnit"></param>
		/// <param name="targetUnit"></param>
		void UpdateUnit(Unit sourceUnit, Unit targetUnit);
        
        /// 
        /// <param name="sourceUnit"></param>
        /// <param name="targetUnit"></param>
        List<Unit> GetUnits();
	}

}