///////////////////////////////////////////////////////////
//  Unit.cs
//  Implementation of the Class Unit
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:19
//  Original author: justo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.HospitalManagement;
using HubaskyHospitalManager.Model.Common;

namespace HubaskyHospitalManager.Model.HospitalManagement
{
	public class Unit 
    {
        private string name;
        private Employee manager;
        private List<Employee> employees;

        public string Name
        {
            get { return name; }
            set { name = value; }
        }

        public Employee Manager
        {
            get { return manager; }
            set { manager = value; }
        }

        public List<Employee> Employees
        {
            get { return employees; }
            set { employees = value; }
        }

		public Unit()
        {

		}

	}//end Unit

}//end namespace HospitalManagement