///////////////////////////////////////////////////////////
//  Unit.cs
//  Implementation of the Class Unit
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:19
//  Original author: justo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.HospitalManagement;
using HubaskyHospitalManager.Model.Common;
using System.ComponentModel.DataAnnotations;

namespace HubaskyHospitalManager.Model.HospitalManagement
{
	public class Unit 
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual Employee Manager { get; set; }
        public virtual List<Employee> Employees { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Web { get; set; }
        
		public Unit()
        {
            Employees = new List<Employee>();
		}

        public Unit(string name, Employee manager, string email, string phone, string web)
        {
            Name = name;
            Manager = manager;
            Email = email;
            Phone = phone;
            Web = web;
            Employees = new List<Employee>();
        }
	}
}