///////////////////////////////////////////////////////////
//  Ward.cs
//  Implementation of the Class Ward
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:19
//  Original author: hazaip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.HospitalManagement;
using HubaskyHospitalManager.Model.Common;

namespace HubaskyHospitalManager.Model.HospitalManagement
{
	public class Ward : Unit 
    {
        public Dictionary<string, string> Procedures { get; set; }

		public Ward()
        {
            Procedures = new Dictionary<string, string>();
		}

        public Ward(int id, string name, Employee manager, List<Employee> employees, Dictionary<string, string> procedures)
        {
            this.Procedures = procedures;
            this.Id = id;
            this.Name = name;
            this.Manager = manager;
            this.Employees = employees;
        }
	}
}