///////////////////////////////////////////////////////////
//  Ward.cs
//  Implementation of the Class Ward
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:19
//  Original author: hazaip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.HospitalManagement;
using HubaskyHospitalManager.Model.Common;
using HubaskyHospitalManager.Model.PatientManagement;

namespace HubaskyHospitalManager.Model.HospitalManagement
{
	public class Ward : Unit 
    {
        public virtual List<ProcedureType> Procedures { get; set; }

		public Ward()
        {
            Procedures = new List<ProcedureType>();
		}

        public Ward(string name, Employee manager, string email, string phone, string web) : base(name, manager, email, phone, web)
        {
            Procedures = new List<ProcedureType>();
        }

        public Ward(int id, string name, Employee manager, List<Employee> employees, List<ProcedureType> procedures)
        {
            this.Procedures = procedures;
            this.Id = id;
            this.Name = name;
            this.Manager = manager;
            this.Employees = employees;
        }

        public Ward(Unit unit)
        {
            Name = unit.Name;
            Manager = unit.Manager;
            Email = unit.Email;
            Phone = unit.Phone;
            Web = unit.Web;
            // Employees = new List<Employee>();
            Procedures = new List<ProcedureType>();
        }
	}
}