///////////////////////////////////////////////////////////
//  ApplicationUser.cs
//  Implementation of the Class ApplicationUser
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:16
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ApplicationManagement;
namespace ApplicationManagement {
	public class ApplicationUser {

		private string name;
		private ApplicationManagement.Role role;

		public ApplicationUser(){

		}

		~ApplicationUser(){

		}

		public string Name{
			get{
				return name;
			}
			set{
				name = value;
			}
		}

	}//end ApplicationUser

}//end namespace ApplicationManagement