///////////////////////////////////////////////////////////
//  ApplicationManager.cs
//  Implementation of the Class ApplicationManager
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:16
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ApplicationManagement;
namespace ApplicationManagement {
	public class ApplicationManager : IApplicationManagement {

		private ApplicationManagement.ApplicationUser applicationUser;

		public ApplicationManager(){

		}

		~ApplicationManager(){

		}

		/// 
		/// <param name="user"></param>
		/// <param name="pass"></param>
		public boolean Authenticate(string user, string pass){

			return null;
		}

		public PatientManager PatientManagement{
			get;
			set;
		}

		public HospitalManager HospitalManagement{
			get;
			set;
		}

		public InventoryManager InventoryManagement{
			get;
			set;
		}

	}//end ApplicationManager

}//end namespace ApplicationManagement