///////////////////////////////////////////////////////////
//  Person.cs
//  Implementation of the Class Person
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:19
//  Original author: Peet
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ApplicationManagement {
	public abstract class Person {

		private string address;
		private DateTime dateOfBirth;
		private string name;
		private string phone;
		private int ssn;

		public Person(){

		}

		~Person(){

		}

		public string Address{
			get{
				return address;
			}
			set{
				address = value;
			}
		}

		public int SSN{
			get{
				return ssn;
			}
		}

		public string Name{
			get{
				return name;
			}
			set{
				name = value;
			}
		}

		public string Phone{
			get{
				return phone;
			}
			set{
				phone = value;
			}
		}

		public DateTime DateOfBirth{
			get{
				return dateOfBirth;
			}
		}

	}//end Person

}//end namespace ApplicationManagement