///////////////////////////////////////////////////////////
//  Role.cs
//  Implementation of the Enumeration Role
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:19
//  Original author: Peet
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ApplicationManagement {
	public enum Role : int {

		Doctor,
		Nurse,
		Laboratorian,
		DataRecorder,
		Administrator

	}//end Role

}//end namespace ApplicationManagement