///////////////////////////////////////////////////////////
//  Gender.cs
//  Implementation of the Class Gender
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:16
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.Common;

namespace HubaskyHospitalManager.Model.Common
{
	public enum Gender
    {

		Female,
		Male

	}//end Gender

}//end namespace PatientManagement