///////////////////////////////////////////////////////////
//  InventoryUnit.cs
//  Implementation of the Class InventoryUnit
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:17
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.Common;

namespace HubaskyHospitalManager.Model.Common
{
	public enum InventoryUnit
    {

		Db,
		Ml,
		Mg

	}//end InventoryUnit

}//end namespace InventoryManagement