///////////////////////////////////////////////////////////
//  Patient.cs
//  Implementation of the Class Patient
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:18
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.Common;
using HubaskyHospitalManager.Model.PatientManagement;

namespace HubaskyHospitalManager.Model.Common
{
	public class Patient : Person
    {
        public int Ssn { get; set; }
        public List<MedicalRecord> MedicalHistory { get; set; }
        public Gender Gender { get; set; }
        
		public Patient()
        {

		}

	}//end Patient

}//end namespace PatientManagement