///////////////////////////////////////////////////////////
//  Role.cs
//  Implementation of the Enumeration Role
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:19
//  Original author: Peet
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.Common;

namespace HubaskyHospitalManager.Model.Common
{
	public enum Role
    {
		Doctor,
		Nurse,
		Laboratorian,
		DataRecorder,
		Administrator
	}
}