///////////////////////////////////////////////////////////
//  State.cs
//  Implementation of the Class State
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:19
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.Common;

namespace HubaskyHospitalManager.Model.Common
{
	public enum State
    {

		New,
		InProgress,
		Closed,
		Paid

	}//end State

}//end namespace PatientManagement