///////////////////////////////////////////////////////////
//  InventoryManager.cs
//  Implementation of the Class InventoryManager
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:17
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ApplicationManagement;
using InventoryManagement;
namespace InventoryManagement {
	public class InventoryManager : IInventoryManagement {

		private int nextId;
		private ApplicationManagement.ApplicationManager appManager;
		private InventoryManagement.InventoryItem inventory;

		public InventoryManager(){

		}

		~InventoryManager(){

		}

		/// 
		/// <param name="name"></param>
		/// <param name="quantity"></param>
		/// <param name="unit"></param>
		public InventoryItem CreateNewInventoryItem(string name, int quantity, InventoryUnit unit){

			return null;
		}

		/// 
		/// <param name="item"></param>
		/// <param name="increment"></param>
		public int IInventoryManagement.IncreaseQuantity(InventoryItem item, int increment){

			return 0;
		}

		public List<InventoryItem> Inventory{
			get;
			set;
		}

		public AppliacationManager AppManager{
			get;
			set;
		}

		/// 
		/// <param name="item"></param>
		/// <param name="increment"></param>
		public int IInventoryManagement.UpdateQuantity(InventoryItem item, int increment){

			return 0;
		}

	}//end InventoryManager

}//end namespace InventoryManagement