///////////////////////////////////////////////////////////
//  InventoryItem.cs
//  Implementation of the Class InventoryItem
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:17
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using InventoryManagement;
namespace InventoryManagement {
	public class InventoryItem {

		private int id;
		private string name;
		private int quantity;
		private InventoryManagement.InventoryUnit unit;

		public InventoryItem(){

		}

		~InventoryItem(){

		}

		public int Id{
			get{
				return id;
			}
		}

		public string Name{
			get{
				return name;
			}
		}

		public int Quantity{
			get{
				return quantity;
			}
		}

		public InventoryUnit Unit{
			get;
			set;
		}

	}//end InventoryItem

}//end namespace InventoryManagement