///////////////////////////////////////////////////////////
//  ApplicationUser.cs
//  Implementation of the Class ApplicationUser
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:16
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.ApplicationManagement;
using HubaskyHospitalManager.Model.Common;

namespace HubaskyHospitalManager.Model.ApplicationManagement
{
	public class ApplicationUser
    {

		private string name;
        private Role role;

        public string Name
        {
            get { return name; }
            set { name = value; }
        }

        public Role Role
        {
            get { return role; }
            set { role = value; }
        }

		public ApplicationUser()
        {

		}

	}//end ApplicationUser

}//end namespace ApplicationManagement