///////////////////////////////////////////////////////////
//  IApplicationManagement.cs
//  Implementation of the Interface IApplicationManagement
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:17
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.ApplicationManagement;

namespace HubaskyHospitalManager.Model.ApplicationManagement
{
	public interface IApplicationManagement  {

		/// 
		/// <param name="user"></param>
		/// <param name="pass"></param>
		bool Authenticate(string user, string pass);
	}//end IApplicationManagement

}//end namespace ApplicationManagement