///////////////////////////////////////////////////////////
//  IApplicationManagement.cs
//  Implementation of the Interface IApplicationManagement
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:17
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.ApplicationManagement;
using HubaskyHospitalManager.Model.Common;

namespace HubaskyHospitalManager.Model.ApplicationManagement
{
	public interface IApplicationManagement  {

		/// 
		/// <param name="user"></param>
		/// <param name="pass"></param>
        Employee Authenticate(string user, string pass);
        Employee Authenticate(string username, string password, Role[] role);
        void Logout();
	}

}