///////////////////////////////////////////////////////////
//  HospitalManagementWindow.cs
//  Implementation of the Class HospitalManagementWindow
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:16
//  Original author: hazaip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class HospitalManagementWindow {

	public HospitalManagementWindow(){

	}

	~HospitalManagementWindow(){

	}

}//end HospitalManagementWindow