///////////////////////////////////////////////////////////
//  InventoryManagementWindow.cs
//  Implementation of the Class InventoryManagementWindow
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:17
//  Original author: hazaip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class InventoryManagementWindow {

	public InventoryManagementWindow(){

	}

	~InventoryManagementWindow(){

	}

}//end InventoryManagementWindow