///////////////////////////////////////////////////////////
//  LoginWindow.cs
//  Implementation of the Class LoginWindow
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:17
//  Original author: hazaip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class LoginWindow {

	public LoginWindow(){

	}

	~LoginWindow(){

	}

}//end LoginWindow