///////////////////////////////////////////////////////////
//  MainWindow.cs
//  Implementation of the Class MainWindow
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:18
//  Original author: hazaip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class MainWindow {

	public MainWindow(){

	}

	~MainWindow(){

	}

}//end MainWindow