///////////////////////////////////////////////////////////
//  ProcedureWindow.cs
//  Implementation of the Class ProcedureWindow
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:19
//  Original author: hazaip
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ProcedureWindow {

	public ProcedureWindow(){

	}

	~ProcedureWindow(){

	}

}//end ProcedureWindow