//merged with SB 20160430_0920
///////////////////////////////////////////////////////////
//  IPatientManagement.cs
//  Implementation of the Interface IPatientManagement
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:17
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.PatientManagement;
using HubaskyHospitalManager.Model.Common;

namespace HubaskyHospitalManager.Model.PatientManagement
{
    public interface IPatientManagement
    {
        void NewPatient(Patient patient);
        void RemovePatient(Patient patient);
        /// 
        /// <param name="patient"></param>
        void UpdatePatient(Patient patientFromUI, Patient patientToDB);


        /// 
        /// <param name="patient"></param>
        MedicalRecord NewMedicalRecord(Patient patient, MedicalRecord medicalRecord);
        void RemoveMedicalRecord(Patient patient, MedicalRecord medicalRecord);

        /// 
        /// <param name="patient"></param>
        Procedure NewProcedure(MedicalRecord medicalrecord, Procedure procedure);
        void RemoveProcedure(MedicalRecord medicalrecord, Procedure procedure);

        ///// 
        ///// <param name="procedure"></param>
        //void CloseProcedure(Procedure procedure);

        ///// 
        ///// <param name="medicalRecord"></param>
        //void CloseMedicalRecord(MedicalRecord medicalRecord);

        /// 
        /// <param name="procedure"></param>
        void UpdateProcedure(Procedure procedureFromUI, Procedure procedureToDB);

        /// 
        /// <param name="patient"></param>
        void UpdateMedicalRecord(MedicalRecord medicalRecordFromUI, MedicalRecord medicalRecordToDB);

        void UpdateAttachments(List<Attachment> filesToSave, List<string> localPathToSave, Procedure procedure);

        void DownloadAttachment(Attachment attachment, string localPath);
    }//end IPatientManagement

}//end namespace PatientManagement