//merged with SB 20160430_0920
///////////////////////////////////////////////////////////
//  IPatientManagement.cs
//  Implementation of the Interface IPatientManagement
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:17
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.PatientManagement;
using HubaskyHospitalManager.Model.Common;

namespace HubaskyHospitalManager.Model.PatientManagement
{
    public interface IPatientManagement
    {
        Patient NewPatient();

        /// 
        /// <param name="patient"></param>
        void UpdatePatient(Patient patientFromUI, Patient patientToDB);

        /// 
        /// <param name="patient"></param>
        MedicalRecord NewMedicalRecord(Patient patient);

        /// 
        /// <param name="patient"></param>
        Procedure NewProcedure(Patient patient);

        /// 
        /// <param name="procedure"></param>
        void CloseProcedure(Procedure procedure);

        /// 
        /// <param name="medicalRecord"></param>
        void CloseMedicalRecord(MedicalRecord medicalRecord);

        /// 
        /// <param name="procedure"></param>
        void UpdateProcedure(Procedure procedureFromUI, Procedure procedureToDB);

        /// 
        /// <param name="patient"></param>
        void UpdateMedicalRecord(MedicalRecord medicalRecordFromUI, MedicalRecord medicalRecordToDB);
    }//end IPatientManagement

}//end namespace PatientManagement