///////////////////////////////////////////////////////////
//  MedicalRecord.cs
//  Implementation of the Class MedicalRecord
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:18
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.PatientManagement;
using HubaskyHospitalManager.Model.Common;
using System.ComponentModel.DataAnnotations;

namespace HubaskyHospitalManager.Model.PatientManagement
{
    public class MedicalRecord
    {
        //egy medical history van, azon belül több medical record, azon belül több procedure
        [Key]
        private readonly string createdTimestamp;

        private string anamnesis;
        private string diagnosis;
        private State state;
        private List<Procedure> procedures;

        public string CreatedTimestamp
        {
            get { return createdTimestamp; }
            //set { createdTimestamp = value; }
        }

        public string Anamnesis
        {
            get { return anamnesis; }
            set { anamnesis = value; }
        }

        public string Diagnosis
        {
            get { return diagnosis; }
            set { diagnosis = value; }
        }

        public State State
        {
            get { return state; }
            set { state = value; }
        }

        public List<Procedure> Procedures
        {
            get { return procedures; }
            set { procedures = value; }
        }

        public MedicalRecord()
        {
            this.createdTimestamp = DateTime.Now.ToString("yyyyMMddHHmmssff");
            this.state = State.New;
            this.diagnosis = "";
            this.procedures = new List<Procedure>();
            this.procedures.Add(new Procedure());

        }



    }//end MedicalRecord

}//end namespace PatientManagement