///////////////////////////////////////////////////////////
//  Procedure.cs
//  Implementation of the Class Procedure
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:19
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using HubaskyHospitalManager.Model.PatientManagement;
using HubaskyHospitalManager.Model.InventoryManagement;
using HubaskyHospitalManager.Model.Common;
using System.ComponentModel.DataAnnotations;

namespace HubaskyHospitalManager.Model.PatientManagement
{
    public class Procedure
    {
        [Key]
        private readonly string createdTimestamp;

        private string lastModifiedTimestamp;
        private List<string> attachments;
        private string name;
        private int price;
        private State state;
        private Employee responsible;
        private List<InventoryItem> inventoryUsage;

        public List<string> Attachments
        {
            get { return attachments; }
            set { attachments = value; }
        }

        public string CreatedTimestamp
        {
            get { return createdTimestamp; }
            //set { createdTimestamp = value; }
        }

        public string LastModifiedTimestamp
        {
            get { return lastModifiedTimestamp; }
            set { lastModifiedTimestamp = value; }
        }

        public string Name
        {
            get { return name; }
            set { name = value; }
        }

        public int Price
        {
            get { return price; }
            set { price = value; }
        }

        public State State
        {
            get { return state; }
            set { state = value; }
        }

        public Employee Responsible
        {
            get { return responsible; }
            set { responsible = value; }
        }

        public List<InventoryItem> InventoryUsage
        {
            get { return inventoryUsage; }
            set { inventoryUsage = value; }
        }

        public Procedure()
        {
            this.createdTimestamp = DateTime.Now.ToString("yyyyMMddHHmmssff");
            this.LastModifiedTimestamp = this.createdTimestamp;

            this.State = State.New;
            this.inventoryUsage = new List<InventoryItem>();
            this.price = 0;
            this.name = "";
            this.attachments = new List<string>();
            //this.responsible //-> nincs inicializálva!
        }


        /// 
        /// <param name="attachment"></param>
        public void AddAttachment(string attachment)
        {

        }

        /// 
        /// <param name="item"></param>
        /// <param name="decrement"></param>
        public int DecreaseQuantity(InventoryItem item, int decrement)
        {
            return 0;
        }

        /// 
        /// <param name="name"></param>
        public List<InventoryItem> SearchInventory(string name)
        {
            return null;
        }

    }//end Procedure

}//end namespace PatientManagement