///////////////////////////////////////////////////////////
//  procedureHistoryPage.cs
//  Implementation of the Class procedureHistoryPage
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:19
//  Original author: justo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class procedureHistoryPage : HttpJspBase {

	public procedureHistoryPage(){

	}

	~procedureHistoryPage(){

	}

	public override void _jspDestroy(){

	}

	public override void _jspInit(){

	}

	/// 
	/// <param name="resp"></param>
	/// <param name="req"></param>
	public override void _jspService(HttpServletResponse resp, HttpServletRequest req){

	}

}//end procedureHistoryPage