///////////////////////////////////////////////////////////
//  Doctor.cs
//  Implementation of the Class Doctor
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:16
//  Original author: justo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace WebDataManagement.hospital.database.domain {
	public class Doctor {

		private String address;
		private int id;
		private String name;
		private String phoneNumber;
		private String role;

		public Doctor(){

		}

		~Doctor(){

		}

		public String getAddress(){

			return "";
		}

		public int getId(){

			return 0;
		}

		public String getName(){

			return "";
		}

		public String getPhoneNumber(){

			return "";
		}

		public Role getRole(){

			return null;
		}

	}//end Doctor

}//end namespace hospital.database.domain