///////////////////////////////////////////////////////////
//  Gender.cs
//  Implementation of the Class Gender
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:16
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace PatientManagement {
	public enum Gender : int {

		FEMALE,
		MALE

	}//end Gender

}//end namespace PatientManagement