///////////////////////////////////////////////////////////
//  MedicalRecord.cs
//  Implementation of the Class MedicalRecord
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:18
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using PatientManagement;
namespace PatientManagement {
	public class MedicalRecord {

		private string symptoms;
		private PatientManagement.State state;
		private List<Procedure> procedures;

		public MedicalRecord(){

		}

		~MedicalRecord(){

		}

		public string Symptoms{
			get{
				return symptoms;
			}
		}

		public List<Procedure> Procedures{
			get;
			set;
		}

		public State State{
			get;
			set;
		}

	}//end MedicalRecord

}//end namespace PatientManagement