///////////////////////////////////////////////////////////
//  PatientManager.cs
//  Implementation of the Class PatientManager
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:18
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using PatientManagement;
using ApplicationManagement;
namespace PatientManagement {
	public class PatientManager : IPatientManagement {

		private ApplicationManagement.ApplicationManager appManager;
		private List<Patient> patients;

		public PatientManager(){

		}

		~PatientManager(){

		}

		/// 
		/// <param name="medicalRecord"></param>
		public void CloseMedicalRecord(MedicalRecord medicalRecord){

		}

		/// 
		/// <param name="procedure"></param>
		public void CloseProcedure(Procedure procedure){

		}

		/// 
		/// <param name="patient"></param>
		public MedicalRecord NewMedicalRecord(Patient patient){

			return null;
		}

		public Patient NewPatient(){

			return null;
		}

		/// 
		/// <param name="patient"></param>
		public Procedure NewProcedure(Patient patient){

			return null;
		}

		/// 
		/// <param name="patient"></param>
		public void UpdateMedicalRecord(Patient patient){

		}

		/// 
		/// <param name="patient"></param>
		public void UpdatePatient(Patient patient){

		}

		/// 
		/// <param name="procedure"></param>
		public void UpdateProcedure(Procedure procedure){

		}

		public List<Patient> Patients{
			get;
			set;
		}

		public ApplicationManager AppManager{
			get;
			set;
		}

	}//end PatientManager

}//end namespace PatientManagement