///////////////////////////////////////////////////////////
//  Person.cs
//  Implementation of the Class Person
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:19
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace PatientManagement {
	public class Person {

		private string address;
		private string name;
		private string phone;
		private DateTime dateOfBirth;

		public Person(){

		}

		~Person(){

		}

	}//end Person

}//end namespace PatientManagement