///////////////////////////////////////////////////////////
//  State.cs
//  Implementation of the Class State
//  Generated by Enterprise Architect
//  Created on:      07-ápr.-2016 12:45:19
//  Original author: Owczarek Artur
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace PatientManagement {
	public enum State : int {

		NEW,
		IN_PROGRESS,
		CLOSED,
		PAID

	}//end State

}//end namespace PatientManagement